tmdwh:
  outputs:
    dev:
      type: postgres
      host: movie-postgres
      user: postgres
      pass: postgres1234
      port: 5432
      dbname: MovieVerse_DB
      schema: dbt
      threads: 4
  target: dev